FROM golang:1.25 AS builder
WORKDIR /src
ARG TARGETOS
ARG TARGETARCH
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -o /out/rbacgraph-web ./cmd/rbacgraph-web

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /out/rbacgraph-web /rbacgraph-web
USER nonroot:nonroot
ENTRYPOINT ["/rbacgraph-web"]
