//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The k8s-role-graph Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	rbacgraph "k8s-role-graph/pkg/apis/rbacgraph"
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*APIGroupPermissions)(nil), (*rbacgraph.APIGroupPermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_APIGroupPermissions_To_rbacgraph_APIGroupPermissions(a.(*APIGroupPermissions), b.(*rbacgraph.APIGroupPermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.APIGroupPermissions)(nil), (*APIGroupPermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_APIGroupPermissions_To_v1alpha1_APIGroupPermissions(a.(*rbacgraph.APIGroupPermissions), b.(*APIGroupPermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GrantingRule)(nil), (*rbacgraph.GrantingRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GrantingRule_To_rbacgraph_GrantingRule(a.(*GrantingRule), b.(*rbacgraph.GrantingRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.GrantingRule)(nil), (*GrantingRule)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_GrantingRule_To_v1alpha1_GrantingRule(a.(*rbacgraph.GrantingRule), b.(*GrantingRule), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Graph)(nil), (*rbacgraph.Graph)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Graph_To_rbacgraph_Graph(a.(*Graph), b.(*rbacgraph.Graph), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.Graph)(nil), (*Graph)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_Graph_To_v1alpha1_Graph(a.(*rbacgraph.Graph), b.(*Graph), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GraphEdge)(nil), (*rbacgraph.GraphEdge)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GraphEdge_To_rbacgraph_GraphEdge(a.(*GraphEdge), b.(*rbacgraph.GraphEdge), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.GraphEdge)(nil), (*GraphEdge)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_GraphEdge_To_v1alpha1_GraphEdge(a.(*rbacgraph.GraphEdge), b.(*GraphEdge), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GraphNode)(nil), (*rbacgraph.GraphNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_GraphNode_To_rbacgraph_GraphNode(a.(*GraphNode), b.(*rbacgraph.GraphNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.GraphNode)(nil), (*GraphNode)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_GraphNode_To_v1alpha1_GraphNode(a.(*rbacgraph.GraphNode), b.(*GraphNode), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NamespaceScope)(nil), (*rbacgraph.NamespaceScope)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope(a.(*NamespaceScope), b.(*rbacgraph.NamespaceScope), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.NamespaceScope)(nil), (*NamespaceScope)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope(a.(*rbacgraph.NamespaceScope), b.(*NamespaceScope), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NonResourceURLEntry)(nil), (*rbacgraph.NonResourceURLEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NonResourceURLEntry_To_rbacgraph_NonResourceURLEntry(a.(*NonResourceURLEntry), b.(*rbacgraph.NonResourceURLEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.NonResourceURLEntry)(nil), (*NonResourceURLEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_NonResourceURLEntry_To_v1alpha1_NonResourceURLEntry(a.(*rbacgraph.NonResourceURLEntry), b.(*NonResourceURLEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NonResourceURLList)(nil), (*rbacgraph.NonResourceURLList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NonResourceURLList_To_rbacgraph_NonResourceURLList(a.(*NonResourceURLList), b.(*rbacgraph.NonResourceURLList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.NonResourceURLList)(nil), (*NonResourceURLList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_NonResourceURLList_To_v1alpha1_NonResourceURLList(a.(*rbacgraph.NonResourceURLList), b.(*NonResourceURLList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NonResourceURLPermissionEntry)(nil), (*rbacgraph.NonResourceURLPermissionEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NonResourceURLPermissionEntry_To_rbacgraph_NonResourceURLPermissionEntry(a.(*NonResourceURLPermissionEntry), b.(*rbacgraph.NonResourceURLPermissionEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.NonResourceURLPermissionEntry)(nil), (*NonResourceURLPermissionEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_NonResourceURLPermissionEntry_To_v1alpha1_NonResourceURLPermissionEntry(a.(*rbacgraph.NonResourceURLPermissionEntry), b.(*NonResourceURLPermissionEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NonResourceURLPermissions)(nil), (*rbacgraph.NonResourceURLPermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NonResourceURLPermissions_To_rbacgraph_NonResourceURLPermissions(a.(*NonResourceURLPermissions), b.(*rbacgraph.NonResourceURLPermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.NonResourceURLPermissions)(nil), (*NonResourceURLPermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_NonResourceURLPermissions_To_v1alpha1_NonResourceURLPermissions(a.(*rbacgraph.NonResourceURLPermissions), b.(*NonResourceURLPermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourceMapRow)(nil), (*rbacgraph.ResourceMapRow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourceMapRow_To_rbacgraph_ResourceMapRow(a.(*ResourceMapRow), b.(*rbacgraph.ResourceMapRow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.ResourceMapRow)(nil), (*ResourceMapRow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_ResourceMapRow_To_v1alpha1_ResourceMapRow(a.(*rbacgraph.ResourceMapRow), b.(*ResourceMapRow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ResourcePermissions)(nil), (*rbacgraph.ResourcePermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResourcePermissions_To_rbacgraph_ResourcePermissions(a.(*ResourcePermissions), b.(*rbacgraph.ResourcePermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.ResourcePermissions)(nil), (*ResourcePermissions)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_ResourcePermissions_To_v1alpha1_ResourcePermissions(a.(*rbacgraph.ResourcePermissions), b.(*ResourcePermissions), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleGraphReview)(nil), (*rbacgraph.RoleGraphReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoleGraphReview_To_rbacgraph_RoleGraphReview(a.(*RoleGraphReview), b.(*rbacgraph.RoleGraphReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RoleGraphReview)(nil), (*RoleGraphReview)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RoleGraphReview_To_v1alpha1_RoleGraphReview(a.(*rbacgraph.RoleGraphReview), b.(*RoleGraphReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleGraphReviewSpec)(nil), (*rbacgraph.RoleGraphReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec(a.(*RoleGraphReviewSpec), b.(*rbacgraph.RoleGraphReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RoleGraphReviewSpec)(nil), (*RoleGraphReviewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec(a.(*rbacgraph.RoleGraphReviewSpec), b.(*RoleGraphReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleGraphReviewStatus)(nil), (*rbacgraph.RoleGraphReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus(a.(*RoleGraphReviewStatus), b.(*rbacgraph.RoleGraphReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RoleGraphReviewStatus)(nil), (*RoleGraphReviewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus(a.(*rbacgraph.RoleGraphReviewStatus), b.(*RoleGraphReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RolePermissionsView)(nil), (*rbacgraph.RolePermissionsView)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RolePermissionsView_To_rbacgraph_RolePermissionsView(a.(*RolePermissionsView), b.(*rbacgraph.RolePermissionsView), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RolePermissionsView)(nil), (*RolePermissionsView)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RolePermissionsView_To_v1alpha1_RolePermissionsView(a.(*rbacgraph.RolePermissionsView), b.(*RolePermissionsView), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RolePermissionsViewSpec)(nil), (*rbacgraph.RolePermissionsViewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec(a.(*RolePermissionsViewSpec), b.(*rbacgraph.RolePermissionsViewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RolePermissionsViewSpec)(nil), (*RolePermissionsViewSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec(a.(*rbacgraph.RolePermissionsViewSpec), b.(*RolePermissionsViewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RolePermissionsViewStatus)(nil), (*rbacgraph.RolePermissionsViewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus(a.(*RolePermissionsViewStatus), b.(*rbacgraph.RolePermissionsViewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RolePermissionsViewStatus)(nil), (*RolePermissionsViewStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus(a.(*rbacgraph.RolePermissionsViewStatus), b.(*RolePermissionsViewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RoleRef)(nil), (*rbacgraph.RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RoleRef_To_rbacgraph_RoleRef(a.(*RoleRef), b.(*rbacgraph.RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RoleRef)(nil), (*RoleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RoleRef_To_v1alpha1_RoleRef(a.(*rbacgraph.RoleRef), b.(*RoleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RuleRef)(nil), (*rbacgraph.RuleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_RuleRef_To_rbacgraph_RuleRef(a.(*RuleRef), b.(*rbacgraph.RuleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.RuleRef)(nil), (*RuleRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_RuleRef_To_v1alpha1_RuleRef(a.(*rbacgraph.RuleRef), b.(*RuleRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Selector)(nil), (*rbacgraph.Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Selector_To_rbacgraph_Selector(a.(*Selector), b.(*rbacgraph.Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.Selector)(nil), (*Selector)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_Selector_To_v1alpha1_Selector(a.(*rbacgraph.Selector), b.(*Selector), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VerbPermission)(nil), (*rbacgraph.VerbPermission)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_VerbPermission_To_rbacgraph_VerbPermission(a.(*VerbPermission), b.(*rbacgraph.VerbPermission), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*rbacgraph.VerbPermission)(nil), (*VerbPermission)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_rbacgraph_VerbPermission_To_v1alpha1_VerbPermission(a.(*rbacgraph.VerbPermission), b.(*VerbPermission), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_APIGroupPermissions_To_rbacgraph_APIGroupPermissions(in *APIGroupPermissions, out *rbacgraph.APIGroupPermissions, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.ResourcesCount = in.ResourcesCount
	out.Resources = *(*[]rbacgraph.ResourcePermissions)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_v1alpha1_APIGroupPermissions_To_rbacgraph_APIGroupPermissions is an autogenerated conversion function.
func Convert_v1alpha1_APIGroupPermissions_To_rbacgraph_APIGroupPermissions(in *APIGroupPermissions, out *rbacgraph.APIGroupPermissions, s conversion.Scope) error {
	return autoConvert_v1alpha1_APIGroupPermissions_To_rbacgraph_APIGroupPermissions(in, out, s)
}

func autoConvert_rbacgraph_APIGroupPermissions_To_v1alpha1_APIGroupPermissions(in *rbacgraph.APIGroupPermissions, out *APIGroupPermissions, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.ResourcesCount = in.ResourcesCount
	out.Resources = *(*[]ResourcePermissions)(unsafe.Pointer(&in.Resources))
	return nil
}

// Convert_rbacgraph_APIGroupPermissions_To_v1alpha1_APIGroupPermissions is an autogenerated conversion function.
func Convert_rbacgraph_APIGroupPermissions_To_v1alpha1_APIGroupPermissions(in *rbacgraph.APIGroupPermissions, out *APIGroupPermissions, s conversion.Scope) error {
	return autoConvert_rbacgraph_APIGroupPermissions_To_v1alpha1_APIGroupPermissions(in, out, s)
}

func autoConvert_v1alpha1_GrantingRule_To_rbacgraph_GrantingRule(in *GrantingRule, out *rbacgraph.GrantingRule, s conversion.Scope) error {
	out.RuleIndex = in.RuleIndex
	out.APIGroups = *(*[]string)(unsafe.Pointer(&in.APIGroups))
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	return nil
}

// Convert_v1alpha1_GrantingRule_To_rbacgraph_GrantingRule is an autogenerated conversion function.
func Convert_v1alpha1_GrantingRule_To_rbacgraph_GrantingRule(in *GrantingRule, out *rbacgraph.GrantingRule, s conversion.Scope) error {
	return autoConvert_v1alpha1_GrantingRule_To_rbacgraph_GrantingRule(in, out, s)
}

func autoConvert_rbacgraph_GrantingRule_To_v1alpha1_GrantingRule(in *rbacgraph.GrantingRule, out *GrantingRule, s conversion.Scope) error {
	out.RuleIndex = in.RuleIndex
	out.APIGroups = *(*[]string)(unsafe.Pointer(&in.APIGroups))
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	return nil
}

// Convert_rbacgraph_GrantingRule_To_v1alpha1_GrantingRule is an autogenerated conversion function.
func Convert_rbacgraph_GrantingRule_To_v1alpha1_GrantingRule(in *rbacgraph.GrantingRule, out *GrantingRule, s conversion.Scope) error {
	return autoConvert_rbacgraph_GrantingRule_To_v1alpha1_GrantingRule(in, out, s)
}

func autoConvert_v1alpha1_Graph_To_rbacgraph_Graph(in *Graph, out *rbacgraph.Graph, s conversion.Scope) error {
	out.Nodes = *(*[]rbacgraph.GraphNode)(unsafe.Pointer(&in.Nodes))
	out.Edges = *(*[]rbacgraph.GraphEdge)(unsafe.Pointer(&in.Edges))
	return nil
}

// Convert_v1alpha1_Graph_To_rbacgraph_Graph is an autogenerated conversion function.
func Convert_v1alpha1_Graph_To_rbacgraph_Graph(in *Graph, out *rbacgraph.Graph, s conversion.Scope) error {
	return autoConvert_v1alpha1_Graph_To_rbacgraph_Graph(in, out, s)
}

func autoConvert_rbacgraph_Graph_To_v1alpha1_Graph(in *rbacgraph.Graph, out *Graph, s conversion.Scope) error {
	out.Nodes = *(*[]GraphNode)(unsafe.Pointer(&in.Nodes))
	out.Edges = *(*[]GraphEdge)(unsafe.Pointer(&in.Edges))
	return nil
}

// Convert_rbacgraph_Graph_To_v1alpha1_Graph is an autogenerated conversion function.
func Convert_rbacgraph_Graph_To_v1alpha1_Graph(in *rbacgraph.Graph, out *Graph, s conversion.Scope) error {
	return autoConvert_rbacgraph_Graph_To_v1alpha1_Graph(in, out, s)
}

func autoConvert_v1alpha1_GraphEdge_To_rbacgraph_GraphEdge(in *GraphEdge, out *rbacgraph.GraphEdge, s conversion.Scope) error {
	out.ID = in.ID
	out.From = in.From
	out.To = in.To
	out.Type = rbacgraph.GraphEdgeType(in.Type)
	out.RuleRefs = *(*[]rbacgraph.RuleRef)(unsafe.Pointer(&in.RuleRefs))
	out.Explain = in.Explain
	return nil
}

// Convert_v1alpha1_GraphEdge_To_rbacgraph_GraphEdge is an autogenerated conversion function.
func Convert_v1alpha1_GraphEdge_To_rbacgraph_GraphEdge(in *GraphEdge, out *rbacgraph.GraphEdge, s conversion.Scope) error {
	return autoConvert_v1alpha1_GraphEdge_To_rbacgraph_GraphEdge(in, out, s)
}

func autoConvert_rbacgraph_GraphEdge_To_v1alpha1_GraphEdge(in *rbacgraph.GraphEdge, out *GraphEdge, s conversion.Scope) error {
	out.ID = in.ID
	out.From = in.From
	out.To = in.To
	out.Type = GraphEdgeType(in.Type)
	out.RuleRefs = *(*[]RuleRef)(unsafe.Pointer(&in.RuleRefs))
	out.Explain = in.Explain
	return nil
}

// Convert_rbacgraph_GraphEdge_To_v1alpha1_GraphEdge is an autogenerated conversion function.
func Convert_rbacgraph_GraphEdge_To_v1alpha1_GraphEdge(in *rbacgraph.GraphEdge, out *GraphEdge, s conversion.Scope) error {
	return autoConvert_rbacgraph_GraphEdge_To_v1alpha1_GraphEdge(in, out, s)
}

func autoConvert_v1alpha1_GraphNode_To_rbacgraph_GraphNode(in *GraphNode, out *rbacgraph.GraphNode, s conversion.Scope) error {
	out.ID = in.ID
	out.Type = rbacgraph.GraphNodeType(in.Type)
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Aggregated = in.Aggregated
	out.AggregationSources = *(*[]string)(unsafe.Pointer(&in.AggregationSources))
	out.MatchedRuleRefs = *(*[]rbacgraph.RuleRef)(unsafe.Pointer(&in.MatchedRuleRefs))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.PodPhase = in.PodPhase
	out.WorkloadKind = in.WorkloadKind
	out.Synthetic = in.Synthetic
	out.HiddenCount = in.HiddenCount
	return nil
}

// Convert_v1alpha1_GraphNode_To_rbacgraph_GraphNode is an autogenerated conversion function.
func Convert_v1alpha1_GraphNode_To_rbacgraph_GraphNode(in *GraphNode, out *rbacgraph.GraphNode, s conversion.Scope) error {
	return autoConvert_v1alpha1_GraphNode_To_rbacgraph_GraphNode(in, out, s)
}

func autoConvert_rbacgraph_GraphNode_To_v1alpha1_GraphNode(in *rbacgraph.GraphNode, out *GraphNode, s conversion.Scope) error {
	out.ID = in.ID
	out.Type = GraphNodeType(in.Type)
	out.Name = in.Name
	out.Namespace = in.Namespace
	out.Aggregated = in.Aggregated
	out.AggregationSources = *(*[]string)(unsafe.Pointer(&in.AggregationSources))
	out.MatchedRuleRefs = *(*[]RuleRef)(unsafe.Pointer(&in.MatchedRuleRefs))
	out.Labels = *(*map[string]string)(unsafe.Pointer(&in.Labels))
	out.Annotations = *(*map[string]string)(unsafe.Pointer(&in.Annotations))
	out.PodPhase = in.PodPhase
	out.WorkloadKind = in.WorkloadKind
	out.Synthetic = in.Synthetic
	out.HiddenCount = in.HiddenCount
	return nil
}

// Convert_rbacgraph_GraphNode_To_v1alpha1_GraphNode is an autogenerated conversion function.
func Convert_rbacgraph_GraphNode_To_v1alpha1_GraphNode(in *rbacgraph.GraphNode, out *GraphNode, s conversion.Scope) error {
	return autoConvert_rbacgraph_GraphNode_To_v1alpha1_GraphNode(in, out, s)
}

func autoConvert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope(in *NamespaceScope, out *rbacgraph.NamespaceScope, s conversion.Scope) error {
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.Strict = in.Strict
	return nil
}

// Convert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope is an autogenerated conversion function.
func Convert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope(in *NamespaceScope, out *rbacgraph.NamespaceScope, s conversion.Scope) error {
	return autoConvert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope(in, out, s)
}

func autoConvert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope(in *rbacgraph.NamespaceScope, out *NamespaceScope, s conversion.Scope) error {
	out.Namespaces = *(*[]string)(unsafe.Pointer(&in.Namespaces))
	out.Strict = in.Strict
	return nil
}

// Convert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope is an autogenerated conversion function.
func Convert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope(in *rbacgraph.NamespaceScope, out *NamespaceScope, s conversion.Scope) error {
	return autoConvert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope(in, out, s)
}

func autoConvert_v1alpha1_NonResourceURLEntry_To_rbacgraph_NonResourceURLEntry(in *NonResourceURLEntry, out *rbacgraph.NonResourceURLEntry, s conversion.Scope) error {
	out.URL = in.URL
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.Roles = *(*[]string)(unsafe.Pointer(&in.Roles))
	return nil
}

// Convert_v1alpha1_NonResourceURLEntry_To_rbacgraph_NonResourceURLEntry is an autogenerated conversion function.
func Convert_v1alpha1_NonResourceURLEntry_To_rbacgraph_NonResourceURLEntry(in *NonResourceURLEntry, out *rbacgraph.NonResourceURLEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_NonResourceURLEntry_To_rbacgraph_NonResourceURLEntry(in, out, s)
}

func autoConvert_rbacgraph_NonResourceURLEntry_To_v1alpha1_NonResourceURLEntry(in *rbacgraph.NonResourceURLEntry, out *NonResourceURLEntry, s conversion.Scope) error {
	out.URL = in.URL
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.Roles = *(*[]string)(unsafe.Pointer(&in.Roles))
	return nil
}

// Convert_rbacgraph_NonResourceURLEntry_To_v1alpha1_NonResourceURLEntry is an autogenerated conversion function.
func Convert_rbacgraph_NonResourceURLEntry_To_v1alpha1_NonResourceURLEntry(in *rbacgraph.NonResourceURLEntry, out *NonResourceURLEntry, s conversion.Scope) error {
	return autoConvert_rbacgraph_NonResourceURLEntry_To_v1alpha1_NonResourceURLEntry(in, out, s)
}

func autoConvert_v1alpha1_NonResourceURLList_To_rbacgraph_NonResourceURLList(in *NonResourceURLList, out *rbacgraph.NonResourceURLList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]rbacgraph.NonResourceURLEntry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_NonResourceURLList_To_rbacgraph_NonResourceURLList is an autogenerated conversion function.
func Convert_v1alpha1_NonResourceURLList_To_rbacgraph_NonResourceURLList(in *NonResourceURLList, out *rbacgraph.NonResourceURLList, s conversion.Scope) error {
	return autoConvert_v1alpha1_NonResourceURLList_To_rbacgraph_NonResourceURLList(in, out, s)
}

func autoConvert_rbacgraph_NonResourceURLList_To_v1alpha1_NonResourceURLList(in *rbacgraph.NonResourceURLList, out *NonResourceURLList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]NonResourceURLEntry)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_rbacgraph_NonResourceURLList_To_v1alpha1_NonResourceURLList is an autogenerated conversion function.
func Convert_rbacgraph_NonResourceURLList_To_v1alpha1_NonResourceURLList(in *rbacgraph.NonResourceURLList, out *NonResourceURLList, s conversion.Scope) error {
	return autoConvert_rbacgraph_NonResourceURLList_To_v1alpha1_NonResourceURLList(in, out, s)
}

func autoConvert_v1alpha1_NonResourceURLPermissionEntry_To_rbacgraph_NonResourceURLPermissionEntry(in *NonResourceURLPermissionEntry, out *rbacgraph.NonResourceURLPermissionEntry, s conversion.Scope) error {
	out.URL = in.URL
	out.Verbs = *(*map[string]rbacgraph.VerbPermission)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_v1alpha1_NonResourceURLPermissionEntry_To_rbacgraph_NonResourceURLPermissionEntry is an autogenerated conversion function.
func Convert_v1alpha1_NonResourceURLPermissionEntry_To_rbacgraph_NonResourceURLPermissionEntry(in *NonResourceURLPermissionEntry, out *rbacgraph.NonResourceURLPermissionEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_NonResourceURLPermissionEntry_To_rbacgraph_NonResourceURLPermissionEntry(in, out, s)
}

func autoConvert_rbacgraph_NonResourceURLPermissionEntry_To_v1alpha1_NonResourceURLPermissionEntry(in *rbacgraph.NonResourceURLPermissionEntry, out *NonResourceURLPermissionEntry, s conversion.Scope) error {
	out.URL = in.URL
	out.Verbs = *(*map[string]VerbPermission)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_rbacgraph_NonResourceURLPermissionEntry_To_v1alpha1_NonResourceURLPermissionEntry is an autogenerated conversion function.
func Convert_rbacgraph_NonResourceURLPermissionEntry_To_v1alpha1_NonResourceURLPermissionEntry(in *rbacgraph.NonResourceURLPermissionEntry, out *NonResourceURLPermissionEntry, s conversion.Scope) error {
	return autoConvert_rbacgraph_NonResourceURLPermissionEntry_To_v1alpha1_NonResourceURLPermissionEntry(in, out, s)
}

func autoConvert_v1alpha1_NonResourceURLPermissions_To_rbacgraph_NonResourceURLPermissions(in *NonResourceURLPermissions, out *rbacgraph.NonResourceURLPermissions, s conversion.Scope) error {
	out.URLsCount = in.URLsCount
	out.URLs = *(*[]rbacgraph.NonResourceURLPermissionEntry)(unsafe.Pointer(&in.URLs))
	return nil
}

// Convert_v1alpha1_NonResourceURLPermissions_To_rbacgraph_NonResourceURLPermissions is an autogenerated conversion function.
func Convert_v1alpha1_NonResourceURLPermissions_To_rbacgraph_NonResourceURLPermissions(in *NonResourceURLPermissions, out *rbacgraph.NonResourceURLPermissions, s conversion.Scope) error {
	return autoConvert_v1alpha1_NonResourceURLPermissions_To_rbacgraph_NonResourceURLPermissions(in, out, s)
}

func autoConvert_rbacgraph_NonResourceURLPermissions_To_v1alpha1_NonResourceURLPermissions(in *rbacgraph.NonResourceURLPermissions, out *NonResourceURLPermissions, s conversion.Scope) error {
	out.URLsCount = in.URLsCount
	out.URLs = *(*[]NonResourceURLPermissionEntry)(unsafe.Pointer(&in.URLs))
	return nil
}

// Convert_rbacgraph_NonResourceURLPermissions_To_v1alpha1_NonResourceURLPermissions is an autogenerated conversion function.
func Convert_rbacgraph_NonResourceURLPermissions_To_v1alpha1_NonResourceURLPermissions(in *rbacgraph.NonResourceURLPermissions, out *NonResourceURLPermissions, s conversion.Scope) error {
	return autoConvert_rbacgraph_NonResourceURLPermissions_To_v1alpha1_NonResourceURLPermissions(in, out, s)
}

func autoConvert_v1alpha1_ResourceMapRow_To_rbacgraph_ResourceMapRow(in *ResourceMapRow, out *rbacgraph.ResourceMapRow, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Resource = in.Resource
	out.Verb = in.Verb
	out.RoleCount = in.RoleCount
	out.BindingCount = in.BindingCount
	out.SubjectCount = in.SubjectCount
	return nil
}

// Convert_v1alpha1_ResourceMapRow_To_rbacgraph_ResourceMapRow is an autogenerated conversion function.
func Convert_v1alpha1_ResourceMapRow_To_rbacgraph_ResourceMapRow(in *ResourceMapRow, out *rbacgraph.ResourceMapRow, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourceMapRow_To_rbacgraph_ResourceMapRow(in, out, s)
}

func autoConvert_rbacgraph_ResourceMapRow_To_v1alpha1_ResourceMapRow(in *rbacgraph.ResourceMapRow, out *ResourceMapRow, s conversion.Scope) error {
	out.APIGroup = in.APIGroup
	out.Resource = in.Resource
	out.Verb = in.Verb
	out.RoleCount = in.RoleCount
	out.BindingCount = in.BindingCount
	out.SubjectCount = in.SubjectCount
	return nil
}

// Convert_rbacgraph_ResourceMapRow_To_v1alpha1_ResourceMapRow is an autogenerated conversion function.
func Convert_rbacgraph_ResourceMapRow_To_v1alpha1_ResourceMapRow(in *rbacgraph.ResourceMapRow, out *ResourceMapRow, s conversion.Scope) error {
	return autoConvert_rbacgraph_ResourceMapRow_To_v1alpha1_ResourceMapRow(in, out, s)
}

func autoConvert_v1alpha1_ResourcePermissions_To_rbacgraph_ResourcePermissions(in *ResourcePermissions, out *rbacgraph.ResourcePermissions, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Phantom = in.Phantom
	out.Verbs = *(*map[string]rbacgraph.VerbPermission)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_v1alpha1_ResourcePermissions_To_rbacgraph_ResourcePermissions is an autogenerated conversion function.
func Convert_v1alpha1_ResourcePermissions_To_rbacgraph_ResourcePermissions(in *ResourcePermissions, out *rbacgraph.ResourcePermissions, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResourcePermissions_To_rbacgraph_ResourcePermissions(in, out, s)
}

func autoConvert_rbacgraph_ResourcePermissions_To_v1alpha1_ResourcePermissions(in *rbacgraph.ResourcePermissions, out *ResourcePermissions, s conversion.Scope) error {
	out.Plural = in.Plural
	out.Phantom = in.Phantom
	out.Verbs = *(*map[string]VerbPermission)(unsafe.Pointer(&in.Verbs))
	return nil
}

// Convert_rbacgraph_ResourcePermissions_To_v1alpha1_ResourcePermissions is an autogenerated conversion function.
func Convert_rbacgraph_ResourcePermissions_To_v1alpha1_ResourcePermissions(in *rbacgraph.ResourcePermissions, out *ResourcePermissions, s conversion.Scope) error {
	return autoConvert_rbacgraph_ResourcePermissions_To_v1alpha1_ResourcePermissions(in, out, s)
}

func autoConvert_v1alpha1_RoleGraphReview_To_rbacgraph_RoleGraphReview(in *RoleGraphReview, out *rbacgraph.RoleGraphReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RoleGraphReview_To_rbacgraph_RoleGraphReview is an autogenerated conversion function.
func Convert_v1alpha1_RoleGraphReview_To_rbacgraph_RoleGraphReview(in *RoleGraphReview, out *rbacgraph.RoleGraphReview, s conversion.Scope) error {
	return autoConvert_v1alpha1_RoleGraphReview_To_rbacgraph_RoleGraphReview(in, out, s)
}

func autoConvert_rbacgraph_RoleGraphReview_To_v1alpha1_RoleGraphReview(in *rbacgraph.RoleGraphReview, out *RoleGraphReview, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbacgraph_RoleGraphReview_To_v1alpha1_RoleGraphReview is an autogenerated conversion function.
func Convert_rbacgraph_RoleGraphReview_To_v1alpha1_RoleGraphReview(in *rbacgraph.RoleGraphReview, out *RoleGraphReview, s conversion.Scope) error {
	return autoConvert_rbacgraph_RoleGraphReview_To_v1alpha1_RoleGraphReview(in, out, s)
}

func autoConvert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec(in *RoleGraphReviewSpec, out *rbacgraph.RoleGraphReviewSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_Selector_To_rbacgraph_Selector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	out.MatchMode = rbacgraph.MatchMode(in.MatchMode)
	out.WildcardMode = rbacgraph.WildcardMode(in.WildcardMode)
	out.IncludeRuleMetadata = in.IncludeRuleMetadata
	if err := Convert_v1alpha1_NamespaceScope_To_rbacgraph_NamespaceScope(&in.NamespaceScope, &out.NamespaceScope, s); err != nil {
		return err
	}
	out.IncludePods = in.IncludePods
	out.IncludeWorkloads = in.IncludeWorkloads
	out.PodPhaseMode = rbacgraph.PodPhaseMode(in.PodPhaseMode)
	out.MaxPodsPerSubject = in.MaxPodsPerSubject
	out.MaxWorkloadsPerPod = in.MaxWorkloadsPerPod
	out.FilterPhantomAPIs = in.FilterPhantomAPIs
	return nil
}

// Convert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec is an autogenerated conversion function.
func Convert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec(in *RoleGraphReviewSpec, out *rbacgraph.RoleGraphReviewSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RoleGraphReviewSpec_To_rbacgraph_RoleGraphReviewSpec(in, out, s)
}

func autoConvert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec(in *rbacgraph.RoleGraphReviewSpec, out *RoleGraphReviewSpec, s conversion.Scope) error {
	if err := Convert_rbacgraph_Selector_To_v1alpha1_Selector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	out.MatchMode = MatchMode(in.MatchMode)
	out.WildcardMode = WildcardMode(in.WildcardMode)
	out.IncludeRuleMetadata = in.IncludeRuleMetadata
	if err := Convert_rbacgraph_NamespaceScope_To_v1alpha1_NamespaceScope(&in.NamespaceScope, &out.NamespaceScope, s); err != nil {
		return err
	}
	out.IncludePods = in.IncludePods
	out.IncludeWorkloads = in.IncludeWorkloads
	out.PodPhaseMode = PodPhaseMode(in.PodPhaseMode)
	out.MaxPodsPerSubject = in.MaxPodsPerSubject
	out.MaxWorkloadsPerPod = in.MaxWorkloadsPerPod
	out.FilterPhantomAPIs = in.FilterPhantomAPIs
	return nil
}

// Convert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec is an autogenerated conversion function.
func Convert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec(in *rbacgraph.RoleGraphReviewSpec, out *RoleGraphReviewSpec, s conversion.Scope) error {
	return autoConvert_rbacgraph_RoleGraphReviewSpec_To_v1alpha1_RoleGraphReviewSpec(in, out, s)
}

func autoConvert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus(in *RoleGraphReviewStatus, out *rbacgraph.RoleGraphReviewStatus, s conversion.Scope) error {
	out.MatchedRoles = in.MatchedRoles
	out.MatchedBindings = in.MatchedBindings
	out.MatchedSubjects = in.MatchedSubjects
	out.MatchedPods = in.MatchedPods
	out.MatchedWorkloads = in.MatchedWorkloads
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	out.KnownGaps = *(*[]string)(unsafe.Pointer(&in.KnownGaps))
	if err := Convert_v1alpha1_Graph_To_rbacgraph_Graph(&in.Graph, &out.Graph, s); err != nil {
		return err
	}
	out.ResourceMap = *(*[]rbacgraph.ResourceMapRow)(unsafe.Pointer(&in.ResourceMap))
	return nil
}

// Convert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus is an autogenerated conversion function.
func Convert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus(in *RoleGraphReviewStatus, out *rbacgraph.RoleGraphReviewStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RoleGraphReviewStatus_To_rbacgraph_RoleGraphReviewStatus(in, out, s)
}

func autoConvert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus(in *rbacgraph.RoleGraphReviewStatus, out *RoleGraphReviewStatus, s conversion.Scope) error {
	out.MatchedRoles = in.MatchedRoles
	out.MatchedBindings = in.MatchedBindings
	out.MatchedSubjects = in.MatchedSubjects
	out.MatchedPods = in.MatchedPods
	out.MatchedWorkloads = in.MatchedWorkloads
	out.Warnings = *(*[]string)(unsafe.Pointer(&in.Warnings))
	out.KnownGaps = *(*[]string)(unsafe.Pointer(&in.KnownGaps))
	if err := Convert_rbacgraph_Graph_To_v1alpha1_Graph(&in.Graph, &out.Graph, s); err != nil {
		return err
	}
	out.ResourceMap = *(*[]ResourceMapRow)(unsafe.Pointer(&in.ResourceMap))
	return nil
}

// Convert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus is an autogenerated conversion function.
func Convert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus(in *rbacgraph.RoleGraphReviewStatus, out *RoleGraphReviewStatus, s conversion.Scope) error {
	return autoConvert_rbacgraph_RoleGraphReviewStatus_To_v1alpha1_RoleGraphReviewStatus(in, out, s)
}

func autoConvert_v1alpha1_RolePermissionsView_To_rbacgraph_RolePermissionsView(in *RolePermissionsView, out *rbacgraph.RolePermissionsView, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_RolePermissionsView_To_rbacgraph_RolePermissionsView is an autogenerated conversion function.
func Convert_v1alpha1_RolePermissionsView_To_rbacgraph_RolePermissionsView(in *RolePermissionsView, out *rbacgraph.RolePermissionsView, s conversion.Scope) error {
	return autoConvert_v1alpha1_RolePermissionsView_To_rbacgraph_RolePermissionsView(in, out, s)
}

func autoConvert_rbacgraph_RolePermissionsView_To_v1alpha1_RolePermissionsView(in *rbacgraph.RolePermissionsView, out *RolePermissionsView, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_rbacgraph_RolePermissionsView_To_v1alpha1_RolePermissionsView is an autogenerated conversion function.
func Convert_rbacgraph_RolePermissionsView_To_v1alpha1_RolePermissionsView(in *rbacgraph.RolePermissionsView, out *RolePermissionsView, s conversion.Scope) error {
	return autoConvert_rbacgraph_RolePermissionsView_To_v1alpha1_RolePermissionsView(in, out, s)
}

func autoConvert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec(in *RolePermissionsViewSpec, out *rbacgraph.RolePermissionsViewSpec, s conversion.Scope) error {
	if err := Convert_v1alpha1_RoleRef_To_rbacgraph_RoleRef(&in.Role, &out.Role, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_Selector_To_rbacgraph_Selector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	out.MatchMode = rbacgraph.MatchMode(in.MatchMode)
	out.WildcardMode = rbacgraph.WildcardMode(in.WildcardMode)
	out.FilterPhantomAPIs = in.FilterPhantomAPIs
	return nil
}

// Convert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec is an autogenerated conversion function.
func Convert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec(in *RolePermissionsViewSpec, out *rbacgraph.RolePermissionsViewSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_RolePermissionsViewSpec_To_rbacgraph_RolePermissionsViewSpec(in, out, s)
}

func autoConvert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec(in *rbacgraph.RolePermissionsViewSpec, out *RolePermissionsViewSpec, s conversion.Scope) error {
	if err := Convert_rbacgraph_RoleRef_To_v1alpha1_RoleRef(&in.Role, &out.Role, s); err != nil {
		return err
	}
	if err := Convert_rbacgraph_Selector_To_v1alpha1_Selector(&in.Selector, &out.Selector, s); err != nil {
		return err
	}
	out.MatchMode = MatchMode(in.MatchMode)
	out.WildcardMode = WildcardMode(in.WildcardMode)
	out.FilterPhantomAPIs = in.FilterPhantomAPIs
	return nil
}

// Convert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec is an autogenerated conversion function.
func Convert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec(in *rbacgraph.RolePermissionsViewSpec, out *RolePermissionsViewSpec, s conversion.Scope) error {
	return autoConvert_rbacgraph_RolePermissionsViewSpec_To_v1alpha1_RolePermissionsViewSpec(in, out, s)
}

func autoConvert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus(in *RolePermissionsViewStatus, out *rbacgraph.RolePermissionsViewStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Scope = rbacgraph.RoleScope(in.Scope)
	out.APIGroups = *(*[]rbacgraph.APIGroupPermissions)(unsafe.Pointer(&in.APIGroups))
	out.NonResourceURLs = (*rbacgraph.NonResourceURLPermissions)(unsafe.Pointer(in.NonResourceURLs))
	return nil
}

// Convert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus is an autogenerated conversion function.
func Convert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus(in *RolePermissionsViewStatus, out *rbacgraph.RolePermissionsViewStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_RolePermissionsViewStatus_To_rbacgraph_RolePermissionsViewStatus(in, out, s)
}

func autoConvert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus(in *rbacgraph.RolePermissionsViewStatus, out *RolePermissionsViewStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Scope = RoleScope(in.Scope)
	out.APIGroups = *(*[]APIGroupPermissions)(unsafe.Pointer(&in.APIGroups))
	out.NonResourceURLs = (*NonResourceURLPermissions)(unsafe.Pointer(in.NonResourceURLs))
	return nil
}

// Convert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus is an autogenerated conversion function.
func Convert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus(in *rbacgraph.RolePermissionsViewStatus, out *RolePermissionsViewStatus, s conversion.Scope) error {
	return autoConvert_rbacgraph_RolePermissionsViewStatus_To_v1alpha1_RolePermissionsViewStatus(in, out, s)
}

func autoConvert_v1alpha1_RoleRef_To_rbacgraph_RoleRef(in *RoleRef, out *rbacgraph.RoleRef, s conversion.Scope) error {
	out.Kind = rbacgraph.RoleRefKind(in.Kind)
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_RoleRef_To_rbacgraph_RoleRef is an autogenerated conversion function.
func Convert_v1alpha1_RoleRef_To_rbacgraph_RoleRef(in *RoleRef, out *rbacgraph.RoleRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_RoleRef_To_rbacgraph_RoleRef(in, out, s)
}

func autoConvert_rbacgraph_RoleRef_To_v1alpha1_RoleRef(in *rbacgraph.RoleRef, out *RoleRef, s conversion.Scope) error {
	out.Kind = RoleRefKind(in.Kind)
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_rbacgraph_RoleRef_To_v1alpha1_RoleRef is an autogenerated conversion function.
func Convert_rbacgraph_RoleRef_To_v1alpha1_RoleRef(in *rbacgraph.RoleRef, out *RoleRef, s conversion.Scope) error {
	return autoConvert_rbacgraph_RoleRef_To_v1alpha1_RoleRef(in, out, s)
}

func autoConvert_v1alpha1_RuleRef_To_rbacgraph_RuleRef(in *RuleRef, out *rbacgraph.RuleRef, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.APIGroup = in.APIGroup
	out.Resource = in.Resource
	out.Subresource = in.Subresource
	out.Verb = in.Verb
	out.ResourceNames = *(*[]string)(unsafe.Pointer(&in.ResourceNames))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	out.SourceObjectUID = in.SourceObjectUID
	out.SourceRuleIndex = in.SourceRuleIndex
	out.Phantom = in.Phantom
	out.UnsupportedVerb = in.UnsupportedVerb
	out.ExpandedRefs = *(*[]rbacgraph.RuleRef)(unsafe.Pointer(&in.ExpandedRefs))
	return nil
}

// Convert_v1alpha1_RuleRef_To_rbacgraph_RuleRef is an autogenerated conversion function.
func Convert_v1alpha1_RuleRef_To_rbacgraph_RuleRef(in *RuleRef, out *rbacgraph.RuleRef, s conversion.Scope) error {
	return autoConvert_v1alpha1_RuleRef_To_rbacgraph_RuleRef(in, out, s)
}

func autoConvert_rbacgraph_RuleRef_To_v1alpha1_RuleRef(in *rbacgraph.RuleRef, out *RuleRef, s conversion.Scope) error {
	out.APIVersion = in.APIVersion
	out.APIGroup = in.APIGroup
	out.Resource = in.Resource
	out.Subresource = in.Subresource
	out.Verb = in.Verb
	out.ResourceNames = *(*[]string)(unsafe.Pointer(&in.ResourceNames))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	out.SourceObjectUID = in.SourceObjectUID
	out.SourceRuleIndex = in.SourceRuleIndex
	out.Phantom = in.Phantom
	out.UnsupportedVerb = in.UnsupportedVerb
	out.ExpandedRefs = *(*[]RuleRef)(unsafe.Pointer(&in.ExpandedRefs))
	return nil
}

// Convert_rbacgraph_RuleRef_To_v1alpha1_RuleRef is an autogenerated conversion function.
func Convert_rbacgraph_RuleRef_To_v1alpha1_RuleRef(in *rbacgraph.RuleRef, out *RuleRef, s conversion.Scope) error {
	return autoConvert_rbacgraph_RuleRef_To_v1alpha1_RuleRef(in, out, s)
}

func autoConvert_v1alpha1_Selector_To_rbacgraph_Selector(in *Selector, out *rbacgraph.Selector, s conversion.Scope) error {
	out.APIGroups = *(*[]string)(unsafe.Pointer(&in.APIGroups))
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.ResourceNames = *(*[]string)(unsafe.Pointer(&in.ResourceNames))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	return nil
}

// Convert_v1alpha1_Selector_To_rbacgraph_Selector is an autogenerated conversion function.
func Convert_v1alpha1_Selector_To_rbacgraph_Selector(in *Selector, out *rbacgraph.Selector, s conversion.Scope) error {
	return autoConvert_v1alpha1_Selector_To_rbacgraph_Selector(in, out, s)
}

func autoConvert_rbacgraph_Selector_To_v1alpha1_Selector(in *rbacgraph.Selector, out *Selector, s conversion.Scope) error {
	out.APIGroups = *(*[]string)(unsafe.Pointer(&in.APIGroups))
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.ResourceNames = *(*[]string)(unsafe.Pointer(&in.ResourceNames))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	return nil
}

// Convert_rbacgraph_Selector_To_v1alpha1_Selector is an autogenerated conversion function.
func Convert_rbacgraph_Selector_To_v1alpha1_Selector(in *rbacgraph.Selector, out *Selector, s conversion.Scope) error {
	return autoConvert_rbacgraph_Selector_To_v1alpha1_Selector(in, out, s)
}

func autoConvert_v1alpha1_VerbPermission_To_rbacgraph_VerbPermission(in *VerbPermission, out *rbacgraph.VerbPermission, s conversion.Scope) error {
	out.Granted = in.Granted
	out.SupportedByAPI = in.SupportedByAPI
	out.Rules = *(*[]rbacgraph.GrantingRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_v1alpha1_VerbPermission_To_rbacgraph_VerbPermission is an autogenerated conversion function.
func Convert_v1alpha1_VerbPermission_To_rbacgraph_VerbPermission(in *VerbPermission, out *rbacgraph.VerbPermission, s conversion.Scope) error {
	return autoConvert_v1alpha1_VerbPermission_To_rbacgraph_VerbPermission(in, out, s)
}

func autoConvert_rbacgraph_VerbPermission_To_v1alpha1_VerbPermission(in *rbacgraph.VerbPermission, out *VerbPermission, s conversion.Scope) error {
	out.Granted = in.Granted
	out.SupportedByAPI = in.SupportedByAPI
	out.Rules = *(*[]GrantingRule)(unsafe.Pointer(&in.Rules))
	return nil
}

// Convert_rbacgraph_VerbPermission_To_v1alpha1_VerbPermission is an autogenerated conversion function.
func Convert_rbacgraph_VerbPermission_To_v1alpha1_VerbPermission(in *rbacgraph.VerbPermission, out *VerbPermission, s conversion.Scope) error {
	return autoConvert_rbacgraph_VerbPermission_To_v1alpha1_VerbPermission(in, out, s)
}
